/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface FzButton {
    'disabled': boolean;
    'upper': boolean;
  }
  interface FzLink {
    'href': string;
    'target': string;
  }
}

declare global {


  interface HTMLFzButtonElement extends Components.FzButton, HTMLStencilElement {}
  var HTMLFzButtonElement: {
    prototype: HTMLFzButtonElement;
    new (): HTMLFzButtonElement;
  };

  interface HTMLFzLinkElement extends Components.FzLink, HTMLStencilElement {}
  var HTMLFzLinkElement: {
    prototype: HTMLFzLinkElement;
    new (): HTMLFzLinkElement;
  };
  interface HTMLElementTagNameMap {
    'fz-button': HTMLFzButtonElement;
    'fz-link': HTMLFzLinkElement;
  }
}

declare namespace LocalJSX {
  interface FzButton {
    'disabled'?: boolean;
    'onClickButton'?: (event: CustomEvent<any>) => void;
    'upper'?: boolean;
  }
  interface FzLink {
    'href'?: string;
    'target'?: string;
  }

  interface IntrinsicElements {
    'fz-button': FzButton;
    'fz-link': FzLink;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'fz-button': LocalJSX.FzButton & JSXBase.HTMLAttributes<HTMLFzButtonElement>;
      'fz-link': LocalJSX.FzLink & JSXBase.HTMLAttributes<HTMLFzLinkElement>;
    }
  }
}


