/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface FLink {
    'href': string;
    'target': string;
  }
}

declare global {


  interface HTMLFLinkElement extends Components.FLink, HTMLStencilElement {}
  var HTMLFLinkElement: {
    prototype: HTMLFLinkElement;
    new (): HTMLFLinkElement;
  };
  interface HTMLElementTagNameMap {
    'f-link': HTMLFLinkElement;
  }
}

declare namespace LocalJSX {
  interface FLink {
    'href'?: string;
    'target'?: string;
  }

  interface IntrinsicElements {
    'f-link': FLink;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'f-link': LocalJSX.FLink & JSXBase.HTMLAttributes<HTMLFLinkElement>;
    }
  }
}


